"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from support.helpers import env, base_path

APP_URL = env("APP_URL", "http://localhost:8000")
WEB_URL = env("WEB_URL", "http://localhost:5173")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1fbqb08t8)b&i_al1((@9lq03n2!7&dz$lrv$*%p8wd2z49gy$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition
INSTALLED_APPS = [

    ## allauth ##
    # Required
    'allauth',
    'allauth.account',
    'allauth.headless',

    # Optional
    'allauth.socialaccount',
    'allauth.mfa',
    'allauth.usersessions',

    'corsheaders',

    ## django ##
    'dj_rest_auth',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'django_vite',

    # If you want registration endpoints:
    #'dj_rest_auth.registration',
    'app',
    'inertia',
    'rest_framework',
    'rest_framework.authtoken'
]

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'inertia.middleware.InertiaMiddleware',
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

REST_USE_JWT=True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # base_path("resources/views"),
            base_path("templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
                # 'inertia.context_processors.inertia'
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Static files
STATIC_ROOT = base_path("public/")
STATIC_URL = "/static/"
STATICFILES_DIRS = []

#VITE
DJANGO_VITE = {
    "default": {
        "dev_mode": True, #env("DEBUG", True, cast=bool),
        "dev_server_protocol": "http",
        "dev_server_host": "localhost", #localhost", #env("VITE_DEV_SERVER_HOST", "localhost"),
        # "dev_server_host": "host.docker.internal",  # localhost", #env("VITE_DEV_SERVER_HOST", "localhost"),
        "dev_server_port": 5173, #env("VITE_DEV_SERVER_PORT", 5173, casts=int),
        # "manifest_path": base_path("public/manifest.json"),
    }
}

# DJANGO_VITE_ASSETS_PATH = base_path("public/"),
DJANGO_VITE_DEV_MODE = True #env("DEBUG", True, cast=bool),
# DJANGO_VITE_DEV_SERVER = "http://host.docker.internal:5173"
DJANGO_VITE_DEV_SERVER = "http://localhost:5173"
DJANGO_VITE_STATIC_URL_PREFIX = "/"


INERTIA_VERSION = '1.0' # defaults to '1.0'
INERTIA_LAYOUT = 'index.html' # required and has no default
# INERTIA_SSR_URL = inertia_settings.INERTIA_SSR_URL
# INERTIA_SSR_ENABLED = inertia_settings.INERTIA_SSR_ENABLED
# INERTIA_JSON_ENCODER = inertia_settings.INERTIA_JSON_ENCODER


# INERTIA_JSON_ENCODER = CustomJsonEncoder # defaults to inertia.utils.InertiaJsonEncoder
# INERTIA_SSR_URL = 'http://localhost:13714' # defaults to http://localhost:13714
# INERTIA_SSR_ENABLED = False # defaults to False
# INERTIA_ENCRYPT_HISTORY = False # defaults to False