# Generated by Django 5.2.6 on 2025-09-30 18:14

from django.db import migrations, models
from support.helpers import generate_idempotency_key


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(default=generate_idempotency_key, editable=False, max_length=100, unique=True),
        ),
    ]
